/*
 * Adddrugframe.java
 *
 * Created on __DATE__, __TIME__
 */

package com.drugframe;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import com.dto.Drug;
import com.model.ComboModel;
import com.model.DrugModel;

/**
 * 
 * @author __USER__
 */
public class ManageDrug extends javax.swing.JInternalFrame {

	/** Creates new form Adddrugframe */
	public ManageDrug(JDesktopPane desktop) {
		this.desktop = desktop;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		replace = new javax.swing.JTextField();
		name = new javax.swing.JTextField();
		price = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		remarks = new javax.swing.JTextArea();
		jLabel6 = new javax.swing.JLabel();
		num = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		addbutton = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		searchbutton = new javax.swing.JButton();
		delbutton = new javax.swing.JButton();
		uptbutton = new javax.swing.JButton();
		search = new javax.swing.JComboBox();

		jLabel1.setText("\u836f\u5242\u4ee3\u53f7");

		jLabel2.setText("\u836f\u5242\u540d\u79f0");

		jLabel3.setText("\u836f\u5242\u4ef7\u683c");

		jLabel4.setText("\u5907\u6ce8");

		jLabel5.setText("\u5143");

		remarks.setColumns(20);
		remarks.setRows(5);
		jScrollPane1.setViewportView(remarks);

		jLabel6.setText("\u6570\u91cf");

		jLabel7.setText("\u4e2a");

		addbutton.setText("\u6dfb\u52a0");
		addbutton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addbuttonActionPerformed(evt);
			}
		});

		jButton2.setText("\u53d6\u6d88");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel8.setText("\u6309\u836f\u5242\u4ee3\u53f7\u641c\u7d22");

		searchbutton.setText("\u641c\u7d22");
		searchbutton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchbuttonActionPerformed(evt);
			}
		});

		delbutton.setText("\u5220\u9664");
		delbutton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				delbuttonActionPerformed(evt);
			}
		});
		search.setEditable(true);
		uptbutton.setText("\u4fee\u6539");
		uptbutton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				uptbuttonActionPerformed(evt);
			}
		});
		// 设置下拉框
		ComboModel m = new ComboModel();
		String[] str = m.combo("select replace from drug");
		search.setModel(new javax.swing.DefaultComboBoxModel(str));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				53,
																				53,
																				53)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.CENTER)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel4))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addComponent(
																																price)
																														.addComponent(
																																num,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																74,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																layout
																																		.createSequentialGroup()
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jLabel7))
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																layout
																																		.createSequentialGroup()
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																		.addComponent(
																																				jLabel5))))
																						.addComponent(
																								name,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								120,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jScrollPane1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								256,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								replace,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								74,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																addbutton)
																														.addComponent(
																																uptbutton))
																										.addGap(
																												56,
																												56,
																												56)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jButton2)
																														.addComponent(
																																delbutton)))))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				38,
																				38,
																				38)
																		.addComponent(
																				jLabel8)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				search,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				95,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				34,
																				34,
																				34)
																		.addComponent(
																				searchbutton)))
										.addContainerGap(22, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(34, 34, 34)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(
																searchbutton)
														.addComponent(
																search,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(34, 34, 34)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																replace,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																name,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jLabel5)
														.addComponent(
																price,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(jLabel7)
														.addComponent(
																num,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				addbutton)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				uptbutton))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				delbutton)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton2)))
										.addContainerGap(51, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	// 搜索药剂相关信息
	private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {
		String r = search.getSelectedItem().toString();
		DrugModel dm = new DrugModel();
		Drug d = dm.queryOne(r);
		if (d.getName() == null) {
			JOptionPane.showMessageDialog(this, "查无此药剂信息");
			return;
		}
		replace.setText(d.getReplace());
		remarks.setText(d.getRemarks());
		num.setText(d.getNum() + "");
		price.setText(d.getPrice() + "");
		name.setText(d.getName());
	}

	// 修改药剂信息
	private void uptbuttonActionPerformed(java.awt.event.ActionEvent evt) {
		if (replace.getText().equals("") || name.getText().equals("")
				|| price.getText().equals("") || num.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "请录入完整信息");
			return;
		}
		DrugModel dm = new DrugModel();
		if (dm.queryOne(replace.getText()).getName() == null
				|| search.getSelectedItem().toString()
						.equals(replace.getText())) {
			String re = remarks.getText() == null ? "" : remarks.getText();
			Drug drug = new Drug();
			drug.setReplace(replace.getText());
			drug.setName(name.getText());
			drug.setPrice(Float.parseFloat(price.getText()));
			drug.setNum(Integer.parseInt(num.getText()));
			drug.setRemarks(re);
			boolean flag = false;
			flag = dm.uptDrug(drug, search.getSelectedItem().toString());
			if (flag == true) {
				JOptionPane.showMessageDialog(this, "修改成功");

				desktop.removeAll();
				DrugTableFrame tableframe = new DrugTableFrame();
				tableframe.setMaximumSize(desktop.getMaximumSize());
				desktop.add(tableframe);
				try {
					tableframe.setMaximizable(true);
					// tableframe.setSelected(true);
				} catch (Exception e) {
				}
				tableframe.setVisible(true);
			} else {
				JOptionPane.showMessageDialog(this, "修改失败");
			}
			this.dispose();
		} else {
			JOptionPane.showMessageDialog(this, "该药剂代号已经存在");
		}
	}

	// 删除药剂信息
	private void delbuttonActionPerformed(java.awt.event.ActionEvent evt) {
		String r = search.getSelectedItem().toString();
		int yes = JOptionPane.showConfirmDialog(null, "确定删除'" + r + "'号药剂？");
		if (yes == 0) {
			DrugModel dm = new DrugModel();
			boolean flag = dm.DelStudent(r);
			if (flag == true) {
				JOptionPane.showMessageDialog(this, "删除成功");
				this.dispose();
				desktop.removeAll();
				DrugTableFrame tableframe = new DrugTableFrame();
				tableframe.setMaximumSize(desktop.getMaximumSize());
				desktop.add(tableframe);
				try {
					tableframe.setMaximizable(true);
					// tableframe.setSelected(true);
				} catch (Exception e) {
				}
				tableframe.setVisible(true);
			} else {
				JOptionPane.showMessageDialog(this, "删除失败");
			}
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	// 增加药剂信息
	private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {
		if (replace.getText().equals("") || name.getText().equals("")
				|| price.getText().equals("") || num.getText().equals("")) {
			JOptionPane.showMessageDialog(this, "请录入完整信息");
			return;
		}

		DrugModel dm = new DrugModel();
		if (dm.queryOne(replace.getText().toString()).getName() != null) {
			JOptionPane.showMessageDialog(this, "改药剂代号已存在");
			return;
		}
		String re = remarks.getText() == null ? "" : remarks.getText();
		Drug drug = new Drug();
		drug.setReplace(replace.getText());
		drug.setName(name.getText());
		drug.setPrice(Float.parseFloat(price.getText()));
		drug.setNum(Integer.parseInt(num.getText()));
		drug.setRemarks(re);
		boolean flag = false;
		flag = dm.addDrug(drug);
		if (flag == true) {
			JOptionPane.showMessageDialog(this, "添加成功");

			desktop.removeAll();
			DrugTableFrame tableframe = new DrugTableFrame();
			tableframe.setMaximumSize(desktop.getMaximumSize());
			desktop.add(tableframe);
			try {
				tableframe.setMaximizable(true);
				// tableframe.setSelected(true);
			} catch (Exception e) {
			}
			tableframe.setVisible(true);
		} else {
			JOptionPane.showMessageDialog(this, "添加失败");
		}
		this.dispose();
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton addbutton;
	private javax.swing.JButton delbutton;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField name;
	private javax.swing.JTextField num;
	private javax.swing.JTextField price;
	private javax.swing.JTextArea remarks;
	private javax.swing.JTextField replace;
	private javax.swing.JComboBox search;
	private javax.swing.JButton searchbutton;
	private javax.swing.JButton uptbutton;
	private JDesktopPane desktop;
	// End of variables declaration//GEN-END:variables

}