/*
 * ManagePatient.java
 *
 * Created on __DATE__, __TIME__
 */

package com.patient;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

import com.dto.Bed;
import com.dto.Patient;
import com.employer.EmployerTableFrame;
import com.model.BedModel;
import com.model.ComboModel;
import com.model.EmployerModel;
import com.model.PatientModel;

/**
 *
 * @author  __USER__
 */
public class ManagePatient extends javax.swing.JInternalFrame {

	/** Creates new form ManagePatient */
	public ManagePatient(JDesktopPane desktop) {
		this.desktop = desktop;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		name = new javax.swing.JTextField();
		sex = new javax.swing.JComboBox();
		doctor = new javax.swing.JComboBox();
		jScrollPane1 = new javax.swing.JScrollPane();
		cation = new javax.swing.JTextArea();
		entertime = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		searchbutton = new javax.swing.JButton();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		room = new javax.swing.JComboBox();
		bed = new javax.swing.JComboBox();
		cancelbutton = new javax.swing.JButton();
		uptbutton = new javax.swing.JButton();
		deletebutton = new javax.swing.JButton();
		addbutton = new javax.swing.JButton();
		search = new javax.swing.JComboBox();
		section = new javax.swing.JComboBox();

		jLabel1.setText("\u75c5\u4eba\u4fe1\u606f\u7ba1\u7406\u754c\u9762");

		jLabel2.setText("\u59d3\u540d");

		jLabel3.setText("\u533b\u751f");

		jLabel4.setText("\u6027\u522b");

		jLabel6.setText("\u72b6\u51b5");

		jLabel7.setText("\u79d1\u5ba4");

		jLabel8.setText("\u5165\u9662\u65f6\u95f4");
		
		//设置选择框的内容
		ComboModel com = new ComboModel();
		
		String[] str1 = com.combo("select id from patient");
		search.setModel(new javax.swing.DefaultComboBoxModel(str1));
		search.setEditable(true);
		//部门
		String[] str2 = com.combo("select name from dept where kind='门诊'");
	
		section.setModel(new javax.swing.DefaultComboBoxModel(str2));
		section.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sectionActionPerformed(evt);
			}
		});
		
		sex.setEditable(true);
		sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "男",
				"女" }));
		//医生
		String sdept = section.getSelectedItem().toString();
		String[] str3 =com.combo("select name from employer where dept='"+sdept+"'");
		doctor = new JComboBox(str3);
		
		
		doctor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				doctorActionPerformed(evt);
			}
		});
		
		cation.setColumns(20);
		cation.setRows(5);
		jScrollPane1.setViewportView(cation);

		entertime.setEditable(false);

		jLabel5.setText("\u6839\u636e\u75c5\u4eba\u75c5\u4f8b\u53f7\u641c\u7d22");

		searchbutton.setText("\u641c\u7d22");
		searchbutton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchbuttonActionPerformed(evt);
			}
		});

		jLabel9.setText("\u75c5\u623f");

		jLabel10.setText("\u75c5\u5e8a\u53f7");
		//病房
		String[] str4 = com.combo("select distinct room from bed where patientid is null ");
		room.setModel(new javax.swing.DefaultComboBoxModel(str4));
		room.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				roomActionPerformed(evt);
			}
		});
		//病床
		String rstr = room.getSelectedItem().toString();
		String[] str5 = com.combo("select bed from bed where room = '"+rstr+"'");
		bed = new JComboBox(str5);

		cancelbutton.setText("\u53d6\u6d88");
		cancelbutton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelbuttonActionPerformed(evt);
			}
		});

		uptbutton.setText("\u4fee\u6539\u4fe1\u606f");
		uptbutton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				uptbuttonActionPerformed(evt);
			}
		});

		deletebutton.setText("\u51fa\u9662");
		deletebutton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deletebuttonActionPerformed(evt);
			}
		});

		addbutton.setText("\u5165\u9662");
		addbutton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addbuttonActionPerformed(evt);
			}
		});


		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap(13, Short.MAX_VALUE)
										.addComponent(jLabel5)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												search,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												145,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(searchbutton).addGap(29,
												29, 29))
						.addGroup(
								layout.createSequentialGroup().addGap(124, 124,
										124).addComponent(jLabel1)
										.addContainerGap(152, Short.MAX_VALUE))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(75, 75, 75)
										.addComponent(addbutton)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(deletebutton)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(uptbutton)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(cancelbutton).addGap(51,
												51, 51))
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel9)
																						.addComponent(
																								jLabel10)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jLabel2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								74,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel4,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								74,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel6))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED))
														.addComponent(jLabel7)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				74,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																room,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																86,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																bed,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																86,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																sex,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																61,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																233,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																entertime,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																133,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addComponent(
																				section,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				0,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				name,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				129,
																				Short.MAX_VALUE)
																		.addComponent(
																				doctor,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				0,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addContainerGap(51, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																searchbutton)
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				search,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel5)))
										.addGap(19, 19, 19)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				name,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								sex,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addGap(
																				33,
																				33,
																				33)))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jLabel7))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				6,
																				6,
																				6)
																		.addComponent(
																				section,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																doctor,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(10, 10, 10)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																11,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																entertime,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																11,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																room,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel10,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																11,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																bed,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				78,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				26,
																				26,
																				26)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								addbutton)
																						.addComponent(
																								deletebutton)
																						.addComponent(
																								uptbutton)
																						.addComponent(
																								cancelbutton)))
														.addComponent(
																jLabel6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																11,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(14, 14, 14)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}
	//更新病人住院信息
	private void uptbuttonActionPerformed(java.awt.event.ActionEvent evt) {
		if(name.getText().equals("")||cation.getText().equals("")){
			JOptionPane.showMessageDialog(this, "请将信息填写完整");
			return;
		}
		int r = Integer.parseInt(search.getSelectedItem().toString());
		PatientModel em = new PatientModel();
		if(em.queryOne(r).getName()==null){
			JOptionPane.showMessageDialog(this, "请选择一个病人信息");
			return;
		}
		Patient p = new Patient();
		p.setName(name.getText());
		p.setBed(Integer.parseInt(bed.getSelectedItem().toString()));
		p.setRoom(room.getSelectedItem().toString());
		p.setCation(cation.getText());
		p.setDoctor(doctor.getSelectedItem().toString());
		p.setSection(section.getSelectedItem().toString());
		p.setSex(sex.getSelectedItem().toString());
		//修改病床信息，先删床信息
		BedModel bmodel = new BedModel();
		Bed b = new Bed();
		b.setId(em.queryOne(r).getBed());
		b.setRoom(em.queryOne(r).getRoom());
		bmodel.uptBed(b);
		//重新加床信息
		b.setPatientid(p.getId());
		bmodel.uptBed(b);
		
		boolean flag = em.uptPatient(p, r);
		if(flag){
			JOptionPane.showMessageDialog(this, "修改病人住院信息成功");
			this.dispose();
			desktop.removeAll();
			PatientTableFrame tableframe = new PatientTableFrame();
			desktop.add(tableframe);
			tableframe.setVisible(true);
		}else{
			JOptionPane.showMessageDialog(this, "修改病人住院信息失败");
		}
	}
	
//删除病人住院信息
	private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {
		int r = Integer.parseInt(search.getSelectedItem().toString());
		PatientModel em = new PatientModel();
		if(em.queryOne(r).getName()==null){
			JOptionPane.showMessageDialog(this, "请选择一个病人信息");
			return;
		}
		int yes = JOptionPane.showConfirmDialog(null,  r + "'号病人确定出院？");
		if (yes == 0) {
			//设置相应的床位信息
			BedModel bmodel = new BedModel();
			Bed b = new Bed();
			b.setId(em.queryOne(r).getBed());
			b.setRoom(em.queryOne(r).getRoom());
			bmodel.uptBed(b);
	
			boolean flag = em.DelPatient(r);
			if (flag) {
				JOptionPane.showMessageDialog(this, "恭喜出院，祝您健康");
				desktop.removeAll();
				PatientTableFrame tableframe = new PatientTableFrame();
				desktop.add(tableframe);
				tableframe.setVisible(true);
			} else {
				JOptionPane.showMessageDialog(this, "删除信息失败");
			}
		}
	}
//查找某病人
	private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {
		int id = Integer.parseInt(search.getSelectedItem().toString());
		PatientModel pmodel = new PatientModel();
		Patient p = pmodel.queryOne(id);
		if(p.getName()==null){
			JOptionPane.showMessageDialog(this, "查无此病人信息");
			return;
		}
		name.setText(p.getName());
		sex.setSelectedItem(p.getSex());
		section.setSelectedItem(p.getSection());
		doctor.setSelectedItem(p.getDoctor());
		entertime.setText(p.getEnetertime().toString());
		room.setSelectedItem(p.getRoom());
		bed.setSelectedItem(p.getBed());
		cation.setText(p.getCation());
	}

	//根据病房取得里面的床位信息
	private void roomActionPerformed(java.awt.event.ActionEvent evt) {
		String rstr = room.getSelectedItem().toString();
		ComboModel com = new ComboModel();
		String[] s = com.combo("select bed from bed where room = '"
				+rstr+"' and patientid is null or patientid="
				+search.getSelectedItem().toString());
		bed.removeAllItems();
		for(int i = 0;i<s.length;i++){
			bed.addItem(s[i]);
		}
	}

	//根据科室来取得科室中的医生信息
	private void sectionActionPerformed(java.awt.event.ActionEvent evt) {
		String deptname = section.getSelectedItem().toString();
		ComboModel com = new ComboModel();
		String[] s = com.combo("select name from employer where dept='"+deptname+"'");
		doctor.removeAllItems();
		for(int i = 0;i<s.length;i++){
			doctor.addItem(s[i]);
		}
	}

	private void doctorActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {
		//增加病人信息
		if(name.getText().equals("")||cation.getText().equals("")){
			JOptionPane.showMessageDialog(this, "请将信息填写完整");
			return;
		}
		Patient p = new Patient();
		p.setName(name.getText());
		p.setBed(Integer.parseInt(bed.getSelectedItem().toString()));
		p.setRoom(room.getSelectedItem().toString());
		p.setCation(cation.getText());
		p.setDoctor(doctor.getSelectedItem().toString());
		p.setSection(section.getSelectedItem().toString());
		p.setSex(sex.getSelectedItem().toString());
		PatientModel patientmodel = new PatientModel();
		boolean flag = patientmodel.addPatient(p);
		if(flag){
			//管理病房
			BedModel bmodel = new BedModel();
			Bed b = new Bed();
			b.setId(p.getBed());
			b.setPatientid(patientmodel.queryId());
			b.setRoom(p.getRoom());
			bmodel.uptBed(b);
			
			JOptionPane.showMessageDialog(this, "增加病人住院信息成功");
			this.dispose();
			desktop.removeAll();
			PatientTableFrame tableframe = new PatientTableFrame();
			desktop.add(tableframe);
			tableframe.setVisible(true);
		}else{
			JOptionPane.showMessageDialog(this, "增加病人住院信息失败");
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton addbutton;
	private javax.swing.JComboBox bed;
	private javax.swing.JButton cancelbutton;
	private javax.swing.JTextArea cation;
	private javax.swing.JButton deletebutton;
	private javax.swing.JComboBox doctor;
	private javax.swing.JTextField entertime;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField name;
	private javax.swing.JComboBox room;
	private javax.swing.JComboBox search;
	private javax.swing.JButton searchbutton;
	private javax.swing.JComboBox section;
	private javax.swing.JComboBox sex;
	private javax.swing.JButton uptbutton;
	private JDesktopPane desktop;
	// End of variables declaration//GEN-END:variables

}